# docker compose version
version: "3.9"

services:
  server:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${DATABASE_NAME}
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_ROOT_DATABASE: "${DATABASE_NAME}"
      MYSQL_ROOT_USERNAME: "${DATABASE_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
    volumes:
      - ./dbdata:/var/lib/mysql
    build: .
