# docker compose version
version: "3.9"

services:
  server:
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
    depends_on:
      - mysql
  mysql:
    image: mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    build: .
